import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
// WHY: atlas.json stays upstream's English file; names-it.json maps lowercase English names to Italian, applied at load. `en` keeps the original for EXPLANATIONS and bilingual search.
// WHY: sentence case (Italian style); globals.css capitalize rules set to none, they Title-Cased every word.
const italian=(en:string,it:Record<string,string>)=>{const t=it[en.toLowerCase()]??en;return t[0].toUpperCase()+t.slice(1);};
const VIEWS:Record<View,string>={'three-quarter':'tre quarti',front:'frontale',side:'laterale',back:'posteriore'};
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});const load=(url:string)=>fetch(url,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Impossibile caricare il catalogo anatomico.');return r.json();});Promise.all([load('/models/atlas.json'),load('/models/names-it.json')]).then(([a,n])=>{const data=a as Atlas,it=n as Record<string,string>;for(const x of [...data.parts,...data.concepts])x.name=italian(x.en=x.name,it);setAtlas(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.en?.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||!!c.en?.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,en:p.en,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> ANATOMIA INTERATTIVA</div><h1>Atlante Umano<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString('it-IT'):'2234'} parti modellate <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Pannelli di esplorazione"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Cerca nell'anatomia"><Search size={18}/><span>Trova una struttura</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="Informazioni sull'atlante" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Livelli anatomici">
   <div className="panel-heading"><span>Sistemi</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Chiudi sistemi"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>Tutti</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Scheletro</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Organi</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Mostra solo: ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Mostra: ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString('it-IT')} parti visibili</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Nascondi tutto</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Trova anatomia"><div className="panel-heading"><span>Trova una struttura</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Chiudi ricerca"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Cuore, femore, nervo cranico…" aria-label="Cerca strutture anatomiche per nome" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>Nessuna struttura corrisponde alla ricerca.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'parte':'parti'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Fino a 80 risultati. Affina la ricerca per trovare strutture più piccole.':'Inizia da un organo principale o cerca tra tutte le strutture.'}</p></section>}
  <nav className="view-controls glass" aria-label="Controlli della visuale">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`Vista ${VIEWS[v]}`} aria-label={`Vista ${VIEWS[v]}`}><span>{['¾','F','L','P'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Metti in pausa la rotazione':'Ruota il corpo'} title="Rotazione automatica" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reimposta vista e livelli" title="Reimposta" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'STRUTTURA SELEZIONATA'):state.explode>.95?'INVENTARIO ANATOMICO':state.explode>.05?'STRUTTURE SEPARATE':'ADULTO · MASCHIO'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Apri i livelli dei sistemi"><Layers3 size={20}/><span>Sistemi</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Scomponi l'anatomia</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assemblato</span><span>Ogni parte</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Riassembla e reimposta"><RotateCcw size={18}/><span>Reimposta</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Trascina per spostare':'Trascina per ruotare'} <b>·</b> Pizzica per lo zoom <b>·</b> Tocca per esaminare</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Fonte e crediti <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparazione dell'anatomia</strong><span>{progress}% · Caricamento di {atlas?.parts.length.toLocaleString('it-IT')??'2234'} parti</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Ricarica il visualizzatore</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMIA'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.en??chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[(chosen.en??chosen.name).toLowerCase()]&&<span className="context-note">Panoramica del sistema · struttura identificata dall'anatomia di origine</span>}<div className="structure-meta"><span>Riferimento atlante<strong>{chosen?.id}</strong></span><span>Parti selezionate<strong>{state.selected.length.toLocaleString('it-IT')}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Strutture incluse</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>E altre {selectedParts.length-50} parti modellate.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">Vedi la fonte anatomica <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Mostra l\'anatomia circostante':'Isola la struttura'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Annulla selezione</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">FONTE E AMBITO</div><SheetTitle className="structure-title">Un corpo, svelato.</SheetTitle><SheetDescription>Esplora l'anatomia di riferimento di un maschio adulto da BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Maschio · BodyParts3D</strong><br/>2234 mesh singole e 3432 concetti denominati da un'anatomia di riferimento di un maschio adulto.</p><p>Questo riferimento non contiene ogni struttura o variante umana. Un concetto denominato può comprendere più parti; ogni mesh di origine viene visualizzata una sola volta.</p><p>I colori e i raggruppamenti per sistema sono pensati per l'esplorazione. La geometria è semplificata per il web e le brevi spiegazioni offrono un contesto educativo generale. È un riferimento anatomico, non uno strumento diagnostico o chirurgico.</p><h3>Fonte</h3><p>BodyParts3D, © The Database Center for Life Science, distribuito con licenza CC Attribution 4.0 International. Modifiche: interfaccia e nomi delle strutture tradotti in italiano.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Licenza del dataset <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Geometria e metadati originali <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Leggi la pubblicazione originale <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
